import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../../app/store';

export interface taskState {
  idCount: number;
  tasks: {
    id: number;
    title: string;
    completed: Boolean;
  }[];
  //どのタスクが選択されているかのstate
  selectedTask: {
    id: number;
    title: string;
    completed: Boolean;
  };
  //モーダルのstate
  isModelOpen: Boolean;
}

const initialState: taskState = {
  idCount: 1,
  tasks: [
    {
      id: 1,
      title: 'TaskA',
      completed: false,
    },
  ],
  selectedTask: {
    id: 0,
    title: '',
    completed: false,
  },
  isModelOpen: false,
};

// export const incrementAsync = createAsyncThunk();

export const taskSlice = createSlice({
  name: 'task',
  initialState,
  reducers: {
    //CreateTask
    createTask: (state, action) => {
      state.idCount++;
      const newTask = {
        id: state.idCount,
        title: action.payload,
        completed: false,
      };
      state.tasks = [newTask, ...state.tasks];
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  // extraReducers: (builder) => {
  //   builder;
  // },
});

export const { createTask } = taskSlice.actions;

//stateの値をstoreに登録する記述。めっちゃ大事。
export const selectTask = (state: RootState): taskState['tasks'] =>
  state.task.tasks;

export default taskSlice.reducer;
